CREATE table IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar (256) NOT NULL,
    email varchar (256) NOT NULL CHECK (email LIKE '%@%.%') UNIQUE,
    CONSTRAINT pk_user PRIMARY KEY (id)
    );

CREATE table IF NOT EXISTS item_request(
    item_request_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar (256),
    requestor INTEGER REFERENCES users (id) ON DELETE RESTRICT,
    created datetime NOT NULL

);

CREATE table IF NOT EXISTS items(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar (40) NOT NULL,
    description varchar (256) NOT NULL,
    available boolean NOT NULL,
    owner INTEGER REFERENCES users (id) ON DELETE RESTRICT,
    request_id INTEGER REFERENCES item_request (item_request_id) ON DELETE RESTRICT
);

CREATE table IF NOT EXISTS booking_status (
    booking_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_status_name varchar (256) NOT NULL
);

CREATE table IF NOT EXISTS bookings(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booking_start TIMESTAMP WITHOUT TIME ZONE,
    booking_end TIMESTAMP WITHOUT TIME ZONE CHECK (booking_start <= bookings.booking_end),
    item_id INTEGER REFERENCES items (id) ON DELETE RESTRICT,
    booker_id INTEGER REFERENCES users (id) ON DELETE RESTRICT,
    booking_status varchar,
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE table IF NOT EXISTS comments(
                                       id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                       text varchar NOT NULL,
                                       item_id INTEGER REFERENCES items (id) ON DELETE RESTRICT,
    author_id INTEGER REFERENCES users (id) ON DELETE RESTRICT,
    created TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comment PRIMARY KEY (id)
    );