CREATE table IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar (256),
    email varchar (256) CHECK (email LIKE '%@%.%') UNIQUE
    );

CREATE table IF NOT EXISTS item_request(
    item_request_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar (256),
    requestor INTEGER REFERENCES users (user_id) ON DELETE RESTRICT,
    created datetime NOT NULL

);

CREATE table IF NOT EXISTS items(
    item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar (40),
    description varchar (256),
    available boolean,
    owner INTEGER REFERENCES users (user_id) ON DELETE RESTRICT,
    request_id INTEGER REFERENCES item_request (item_request_id) ON DELETE RESTRICT
);

CREATE table IF NOT EXISTS booking_status (
    booking_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_status_name varchar (256) NOT NULL
);

CREATE table IF NOT EXISTS bookings(
    booking_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_start datetime NOT NULL,
    booking_end datetime NOT NULL CHECK (booking_start <= bookings.booking_end),
    item_id INTEGER REFERENCES items (item_id) ON DELETE RESTRICT,
    booker_id INTEGER REFERENCES users (user_id) ON DELETE RESTRICT,
    booking_status_id INTEGER REFERENCES booking_status (booking_status_id) ON DELETE RESTRICT
);